permalink: /posts/:title
markdown: kramdown

gems:
  - jekyll-sitemap

name: Sebastian Roming
url: https://sebastianroming.github.io
description: A software craftsman from southern germany.
twitter: sebastianroming
facebook: sebastian.roming
